#!/usr/bin/env bash
#mkdir -p $XDG_CONFIG_HOME/nvim/plugin
#mkdir -p $XDG_CONFIG_HOME/nvim/after/plugin
#mkdir -p $XDG_CONFIG_HOME/nvim/lua/lqf
#mkdir -p $XDG_CONFIG_HOME/nvim/lua/lsp
#mkdir -p $XDG_CONFIG_HOME/nvim/lua/plugin
mkdir -p $XDG_CONFIG_HOME/nvim/ftplugin
mkdir -p $XDG_CONFIG_HOME/tmux/tpm
mkdir -p $XDG_CONFIG_HOME/nvim/lua/control
mkdir -p $XDG_CONFIG_HOME/nvim/lua/features

# link wholesale
for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
	if [[ $f =~ control|features|ftplugin ]]; then
	    rm -rf $XDG_CONFIG_HOME/nvim/$f
	    ln -s ~/.dotfiles/$f $XDG_CONFIG_HOME/nvim/$f
	    echo $f
    fi
done

for f in `find . -regex ".*\.toml$"`; do
    rm -rf $XDG_CONFIG_HOME/$f
    ln -s ~/.dotfiles/$f $XDG_CONFIG_HOME/$f
done

for f in `find . -regex ".*tmux.conf$\|.*tmux-.*\.sh$"`; do
    rm -rf $XDG_CONFIG_HOME/tmux/$f
    ln -s ~/.dotfiles/$f $XDG_CONFIG_HOME/tmux/$f
done
